version: '3'

services:
  grafana:
    user: root
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data:/var/lib/grafana
    depends_on:
      - loki
  
  loki:
    user: root
    image: grafana/loki
    container_name: grafana-loki
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ./loki-data:/loki
